# --- DataSource (local con Docker Desktop) ---
spring.datasource.url=jdbc:mysql://localhost:3306/tienda?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=password1

# --- JPA: para desarrollo ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Opcional: prefijo para tus endpoints ---
# server.servlet.context-path=/api

